# LMSP2P — Buat semua akun PIC (PowerShell)
# Jalankan: .\create-all-pic.ps1
# Dari root folder project

Write-Host "Membuat akun PIC Provinsi (38 akun)..." -ForegroundColor Cyan

node prisma/create-pic.js PIC_PROVINSI "pic_prov_aceh" "P2P_Prov_01!" "Aceh"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_bali" "P2P_Prov_02!" "Bali"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_bangka_belitung" "P2P_Prov_03!" "Bangka Belitung"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_banten" "P2P_Prov_04!" "Banten"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_bengkulu" "P2P_Prov_05!" "Bengkulu"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_di_yogyakarta" "P2P_Prov_06!" "Di Yogyakarta"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_dki_jakarta" "P2P_Prov_07!" "Dki Jakarta"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_gorontalo" "P2P_Prov_08!" "Gorontalo"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_jambi" "P2P_Prov_09!" "Jambi"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_jawa_barat" "P2P_Prov_10!" "Jawa Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_jawa_tengah" "P2P_Prov_11!" "Jawa Tengah"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_jawa_timur" "P2P_Prov_12!" "Jawa Timur"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kalimantan_barat" "P2P_Prov_13!" "Kalimantan Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kalimantan_selatan" "P2P_Prov_14!" "Kalimantan Selatan"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kalimantan_tengah" "P2P_Prov_15!" "Kalimantan Tengah"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kalimantan_timur" "P2P_Prov_16!" "Kalimantan Timur"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kalimantan_utara" "P2P_Prov_17!" "Kalimantan Utara"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_kepulauan_riau" "P2P_Prov_18!" "Kepulauan Riau"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_lampung" "P2P_Prov_19!" "Lampung"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_maluku" "P2P_Prov_20!" "Maluku"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_maluku_utara" "P2P_Prov_21!" "Maluku Utara"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_nusa_tenggara_barat" "P2P_Prov_22!" "Nusa Tenggara Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_nusa_tenggara_timur" "P2P_Prov_23!" "Nusa Tenggara Timur"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua" "P2P_Prov_24!" "Papua"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua_barat" "P2P_Prov_25!" "Papua Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua_barat_daya" "P2P_Prov_26!" "Papua Barat Daya"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua_pegunungan" "P2P_Prov_27!" "Papua Pegunungan"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua_selatan" "P2P_Prov_28!" "Papua Selatan"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_papua_tengah" "P2P_Prov_29!" "Papua Tengah"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_riau" "P2P_Prov_30!" "Riau"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sulawesi_barat" "P2P_Prov_31!" "Sulawesi Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sulawesi_selatan" "P2P_Prov_32!" "Sulawesi Selatan"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sulawesi_tengah" "P2P_Prov_33!" "Sulawesi Tengah"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sulawesi_tenggara" "P2P_Prov_34!" "Sulawesi Tenggara"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sulawesi_utara" "P2P_Prov_35!" "Sulawesi Utara"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sumatera_barat" "P2P_Prov_36!" "Sumatera Barat"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sumatera_selatan" "P2P_Prov_37!" "Sumatera Selatan"
node prisma/create-pic.js PIC_PROVINSI "pic_prov_sumatera_utara" "P2P_Prov_38!" "Sumatera Utara"

Write-Host "Membuat akun PIC Kabupaten/Kota (540 akun)..." -ForegroundColor Cyan

Write-Host "  -- Aceh" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_bar" "P2P_0001!" "Aceh" "Kab. Aceh Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_bar" "P2P_0002!" "Aceh" "Kab. Aceh Barat Daya"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_bes" "P2P_0003!" "Aceh" "Kab. Aceh Besar"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_jay" "P2P_0004!" "Aceh" "Kab. Aceh Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_sel" "P2P_0005!" "Aceh" "Kab. Aceh Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_sin" "P2P_0006!" "Aceh" "Kab. Aceh Singkil"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_tam" "P2P_0007!" "Aceh" "Kab. Aceh Tamiang"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_ten" "P2P_0008!" "Aceh" "Kab. Aceh Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_ten" "P2P_0009!" "Aceh" "Kab. Aceh Tenggara"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_tim" "P2P_0010!" "Aceh" "Kab. Aceh Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_aceh_uta" "P2P_0011!" "Aceh" "Kab. Aceh Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_bener_me" "P2P_0012!" "Aceh" "Kab. Bener Meriah"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_bireuen" "P2P_0013!" "Aceh" "Kab. Bireuen"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_gayo_lue" "P2P_0014!" "Aceh" "Kab. Gayo Lues"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_nagan_ra" "P2P_0015!" "Aceh" "Kab. Nagan Raya"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_pidie" "P2P_0016!" "Aceh" "Kab. Pidie"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_pidie_ja" "P2P_0017!" "Aceh" "Kab. Pidie Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_simeulue" "P2P_0018!" "Aceh" "Kab. Simeulue"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_banda_ac" "P2P_0019!" "Aceh" "Kota Banda Aceh"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_langsa" "P2P_0020!" "Aceh" "Kota Langsa"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_lhokseum" "P2P_0021!" "Aceh" "Kota Lhokseumawe"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_sabang" "P2P_0022!" "Aceh" "Kota Sabang"
node prisma/create-pic.js PIC_KABKOTA "pic_aceh_subuluss" "P2P_0023!" "Aceh" "Kota Subulussalam"
Write-Host "  -- Bali" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_bali_badung" "P2P_0024!" "Bali" "Kab. Badung"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_bangli" "P2P_0025!" "Bali" "Kab. Bangli"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_buleleng" "P2P_0026!" "Bali" "Kab. Buleleng"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_gianyar" "P2P_0027!" "Bali" "Kab. Gianyar"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_jembrana" "P2P_0028!" "Bali" "Kab. Jembrana"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_karangas" "P2P_0029!" "Bali" "Kab. Karangasem"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_klungkun" "P2P_0030!" "Bali" "Kab. Klungkung"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_tabanan" "P2P_0031!" "Bali" "Kab. Tabanan"
node prisma/create-pic.js PIC_KABKOTA "pic_bali_denpasar" "P2P_0032!" "Bali" "Kota Denpasar"
Write-Host "  -- Bangka Belitung" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_bangka" "P2P_0033!" "Bangka Belitung" "Kab. Bangka"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_bangka_b" "P2P_0034!" "Bangka Belitung" "Kab. Bangka Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_bangka_s" "P2P_0035!" "Bangka Belitung" "Kab. Bangka Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_bangka_t" "P2P_0036!" "Bangka Belitung" "Kab. Bangka Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_belitung" "P2P_0037!" "Bangka Belitung" "Kab. Belitung"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_belitung" "P2P_0038!" "Bangka Belitung" "Kab. Belitung Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_bangka_pangkalp" "P2P_0039!" "Bangka Belitung" "Kota Pangkalpinang"
Write-Host "  -- Banten" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_banten_lebak" "P2P_0040!" "Banten" "Kab. Lebak"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_pandegla" "P2P_0041!" "Banten" "Kab. Pandeglang"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_serang" "P2P_0042!" "Banten" "Kab. Serang"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_tangeran" "P2P_0043!" "Banten" "Kab. Tangerang"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_cilegon" "P2P_0044!" "Banten" "Kota Cilegon"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_serang" "P2P_0045!" "Banten" "Kota Serang"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_tangeran" "P2P_0046!" "Banten" "Kota Tangerang"
node prisma/create-pic.js PIC_KABKOTA "pic_banten_tangeran" "P2P_0047!" "Banten" "Kota Tangerang Selatan"
Write-Host "  -- Bengkulu" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_bengkulu" "P2P_0048!" "Bengkulu" "Kab. Bengkulu Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_bengkulu" "P2P_0049!" "Bengkulu" "Kab. Bengkulu Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_bengkulu" "P2P_0050!" "Bengkulu" "Kab. Bengkulu Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_kaur" "P2P_0051!" "Bengkulu" "Kab. Kaur"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_kepahian" "P2P_0052!" "Bengkulu" "Kab. Kepahiang"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_lebong" "P2P_0053!" "Bengkulu" "Kab. Lebong"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_mukomuko" "P2P_0054!" "Bengkulu" "Kab. Mukomuko"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_rejang_l" "P2P_0055!" "Bengkulu" "Kab. Rejang Lebong"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_seluma" "P2P_0056!" "Bengkulu" "Kab. Seluma"
node prisma/create-pic.js PIC_KABKOTA "pic_bengku_bengkulu" "P2P_0057!" "Bengkulu" "Kota Bengkulu"
Write-Host "  -- Di Yogyakarta" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_di_yog_bantul" "P2P_0058!" "Di Yogyakarta" "Kab. Bantul"
node prisma/create-pic.js PIC_KABKOTA "pic_di_yog_gunungki" "P2P_0059!" "Di Yogyakarta" "Kab. Gunungkidul"
node prisma/create-pic.js PIC_KABKOTA "pic_di_yog_kulon_pr" "P2P_0060!" "Di Yogyakarta" "Kab. Kulon Progo"
node prisma/create-pic.js PIC_KABKOTA "pic_di_yog_sleman" "P2P_0061!" "Di Yogyakarta" "Kab. Sleman"
node prisma/create-pic.js PIC_KABKOTA "pic_di_yog_yogyakar" "P2P_0062!" "Di Yogyakarta" "Kota Yogyakarta"
Write-Host "  -- Dki Jakarta" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_kepu" "P2P_0063!" "Dki Jakarta" "Kab. Adm. Kepulauan Seribu"
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_jaka" "P2P_0064!" "Dki Jakarta" "Kota Adm. Jakarta Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_jaka" "P2P_0065!" "Dki Jakarta" "Kota Adm. Jakarta Pusat"
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_jaka" "P2P_0066!" "Dki Jakarta" "Kota Adm. Jakarta Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_jaka" "P2P_0067!" "Dki Jakarta" "Kota Adm. Jakarta Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_dki_ja_adm_jaka" "P2P_0068!" "Dki Jakarta" "Kota Adm. Jakarta Utara"
Write-Host "  -- Gorontalo" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_goront_boalemo" "P2P_0069!" "Gorontalo" "Kab. Boalemo"
node prisma/create-pic.js PIC_KABKOTA "pic_goront_bone_bol" "P2P_0070!" "Gorontalo" "Kab. Bone Bolango"
node prisma/create-pic.js PIC_KABKOTA "pic_goront_gorontal" "P2P_0071!" "Gorontalo" "Kab. Gorontalo"
node prisma/create-pic.js PIC_KABKOTA "pic_goront_gorontal" "P2P_0072!" "Gorontalo" "Kab. Gorontalo Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_goront_pohuwato" "P2P_0073!" "Gorontalo" "Kab. Pohuwato"
node prisma/create-pic.js PIC_KABKOTA "pic_goront_gorontal" "P2P_0074!" "Gorontalo" "Kota Gorontalo"
Write-Host "  -- Jambi" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_batangha" "P2P_0075!" "Jambi" "Kab. Batanghari"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_bungo" "P2P_0076!" "Jambi" "Kab. Bungo"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_kerinci" "P2P_0077!" "Jambi" "Kab. Kerinci"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_merangin" "P2P_0078!" "Jambi" "Kab. Merangin"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_muaro_ja" "P2P_0079!" "Jambi" "Kab. Muaro Jambi"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_sarolang" "P2P_0080!" "Jambi" "Kab. Sarolangun"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_tanjung_" "P2P_0081!" "Jambi" "Kab. Tanjung Jabung Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_tanjung_" "P2P_0082!" "Jambi" "Kab. Tanjung Jabung Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_tebo" "P2P_0083!" "Jambi" "Kab. Tebo"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_jambi" "P2P_0084!" "Jambi" "Kota Jambi"
node prisma/create-pic.js PIC_KABKOTA "pic_jambi_sungai_p" "P2P_0085!" "Jambi" "Kota Sungai Penuh"
Write-Host "  -- Jawa Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bandung" "P2P_0086!" "Jawa Barat" "Kab. Bandung"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bandung_" "P2P_0087!" "Jawa Barat" "Kab. Bandung Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bekasi" "P2P_0088!" "Jawa Barat" "Kab. Bekasi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bogor" "P2P_0089!" "Jawa Barat" "Kab. Bogor"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_ciamis" "P2P_0090!" "Jawa Barat" "Kab. Ciamis"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_cianjur" "P2P_0091!" "Jawa Barat" "Kab. Cianjur"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_cirebon" "P2P_0092!" "Jawa Barat" "Kab. Cirebon"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_garut" "P2P_0093!" "Jawa Barat" "Kab. Garut"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_indramay" "P2P_0094!" "Jawa Barat" "Kab. Indramayu"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_karawang" "P2P_0095!" "Jawa Barat" "Kab. Karawang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_kuningan" "P2P_0096!" "Jawa Barat" "Kab. Kuningan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_majaleng" "P2P_0097!" "Jawa Barat" "Kab. Majalengka"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_panganda" "P2P_0098!" "Jawa Barat" "Kab. Pangandaran"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_purwakar" "P2P_0099!" "Jawa Barat" "Kab. Purwakarta"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_subang" "P2P_0100!" "Jawa Barat" "Kab. Subang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_sukabumi" "P2P_0101!" "Jawa Barat" "Kab. Sukabumi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_sumedang" "P2P_0102!" "Jawa Barat" "Kab. Sumedang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_tasikmal" "P2P_0103!" "Jawa Barat" "Kab. Tasikmalaya"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bandung" "P2P_0104!" "Jawa Barat" "Kota Bandung"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_banjar" "P2P_0105!" "Jawa Barat" "Kota Banjar"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bekasi" "P2P_0106!" "Jawa Barat" "Kota Bekasi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_bogor" "P2P_0107!" "Jawa Barat" "Kota Bogor"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_cimahi" "P2P_0108!" "Jawa Barat" "Kota Cimahi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_cirebon" "P2P_0109!" "Jawa Barat" "Kota Cirebon"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_depok" "P2P_0110!" "Jawa Barat" "Kota Depok"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_sukabumi" "P2P_0111!" "Jawa Barat" "Kota Sukabumi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_b_tasikmal" "P2P_0112!" "Jawa Barat" "Kota Tasikmalaya"
Write-Host "  -- Jawa Tengah" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_banjarne" "P2P_0113!" "Jawa Tengah" "Kab. Banjarnegara"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_banyumas" "P2P_0114!" "Jawa Tengah" "Kab. Banyumas"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_batang" "P2P_0115!" "Jawa Tengah" "Kab. Batang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_blora" "P2P_0116!" "Jawa Tengah" "Kab. Blora"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_boyolali" "P2P_0117!" "Jawa Tengah" "Kab. Boyolali"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_brebes" "P2P_0118!" "Jawa Tengah" "Kab. Brebes"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_cilacap" "P2P_0119!" "Jawa Tengah" "Kab. Cilacap"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_demak" "P2P_0120!" "Jawa Tengah" "Kab. Demak"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_grobogan" "P2P_0121!" "Jawa Tengah" "Kab. Grobogan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_jepara" "P2P_0122!" "Jawa Tengah" "Kab. Jepara"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_karangan" "P2P_0123!" "Jawa Tengah" "Kab. Karanganyar"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_kebumen" "P2P_0124!" "Jawa Tengah" "Kab. Kebumen"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_kendal" "P2P_0125!" "Jawa Tengah" "Kab. Kendal"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_klaten" "P2P_0126!" "Jawa Tengah" "Kab. Klaten"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_kudus" "P2P_0127!" "Jawa Tengah" "Kab. Kudus"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_magelang" "P2P_0128!" "Jawa Tengah" "Kab. Magelang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pati" "P2P_0129!" "Jawa Tengah" "Kab. Pati"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pekalong" "P2P_0130!" "Jawa Tengah" "Kab. Pekalongan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pemalang" "P2P_0131!" "Jawa Tengah" "Kab. Pemalang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_purbalin" "P2P_0132!" "Jawa Tengah" "Kab. Purbalingga"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_purworej" "P2P_0133!" "Jawa Tengah" "Kab. Purworejo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_rembang" "P2P_0134!" "Jawa Tengah" "Kab. Rembang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_semarang" "P2P_0135!" "Jawa Tengah" "Kab. Semarang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_sragen" "P2P_0136!" "Jawa Tengah" "Kab. Sragen"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_sukoharj" "P2P_0137!" "Jawa Tengah" "Kab. Sukoharjo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_tegal" "P2P_0138!" "Jawa Tengah" "Kab. Tegal"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_temanggu" "P2P_0139!" "Jawa Tengah" "Kab. Temanggung"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_wonogiri" "P2P_0140!" "Jawa Tengah" "Kab. Wonogiri"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_wonosobo" "P2P_0141!" "Jawa Tengah" "Kab. Wonosobo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_magelang" "P2P_0142!" "Jawa Tengah" "Kota Magelang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pekalong" "P2P_0143!" "Jawa Tengah" "Kota Pekalongan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_salatiga" "P2P_0144!" "Jawa Tengah" "Kota Salatiga"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_semarang" "P2P_0145!" "Jawa Tengah" "Kota Semarang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_surakart" "P2P_0146!" "Jawa Tengah" "Kota Surakarta"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_tegal" "P2P_0147!" "Jawa Tengah" "Kota Tegal"
Write-Host "  -- Jawa Timur" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_bangkala" "P2P_0148!" "Jawa Timur" "Kab. Bangkalan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_banyuwan" "P2P_0149!" "Jawa Timur" "Kab. Banyuwangi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_blitar" "P2P_0150!" "Jawa Timur" "Kab. Blitar"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_bojonego" "P2P_0151!" "Jawa Timur" "Kab. Bojonegoro"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_bondowos" "P2P_0152!" "Jawa Timur" "Kab. Bondowoso"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_gresik" "P2P_0153!" "Jawa Timur" "Kab. Gresik"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_jember" "P2P_0154!" "Jawa Timur" "Kab. Jember"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_jombang" "P2P_0155!" "Jawa Timur" "Kab. Jombang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_kediri" "P2P_0156!" "Jawa Timur" "Kab. Kediri"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_lamongan" "P2P_0157!" "Jawa Timur" "Kab. Lamongan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_lumajang" "P2P_0158!" "Jawa Timur" "Kab. Lumajang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_madiun" "P2P_0159!" "Jawa Timur" "Kab. Madiun"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_magetan" "P2P_0160!" "Jawa Timur" "Kab. Magetan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_malang" "P2P_0161!" "Jawa Timur" "Kab. Malang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_mojokert" "P2P_0162!" "Jawa Timur" "Kab. Mojokerto"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_nganjuk" "P2P_0163!" "Jawa Timur" "Kab. Nganjuk"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_ngawi" "P2P_0164!" "Jawa Timur" "Kab. Ngawi"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pacitan" "P2P_0165!" "Jawa Timur" "Kab. Pacitan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pamekasa" "P2P_0166!" "Jawa Timur" "Kab. Pamekasan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pasuruan" "P2P_0167!" "Jawa Timur" "Kab. Pasuruan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_ponorogo" "P2P_0168!" "Jawa Timur" "Kab. Ponorogo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_probolin" "P2P_0169!" "Jawa Timur" "Kab. Probolinggo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_sampang" "P2P_0170!" "Jawa Timur" "Kab. Sampang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_sidoarjo" "P2P_0171!" "Jawa Timur" "Kab. Sidoarjo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_situbond" "P2P_0172!" "Jawa Timur" "Kab. Situbondo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_sumenep" "P2P_0173!" "Jawa Timur" "Kab. Sumenep"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_trenggal" "P2P_0174!" "Jawa Timur" "Kab. Trenggalek"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_tuban" "P2P_0175!" "Jawa Timur" "Kab. Tuban"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_tulungag" "P2P_0176!" "Jawa Timur" "Kab. Tulungagung"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_batu" "P2P_0177!" "Jawa Timur" "Kota Batu"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_blitar" "P2P_0178!" "Jawa Timur" "Kota Blitar"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_kediri" "P2P_0179!" "Jawa Timur" "Kota Kediri"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_madiun" "P2P_0180!" "Jawa Timur" "Kota Madiun"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_malang" "P2P_0181!" "Jawa Timur" "Kota Malang"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_mojokert" "P2P_0182!" "Jawa Timur" "Kota Mojokerto"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_pasuruan" "P2P_0183!" "Jawa Timur" "Kota Pasuruan"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_probolin" "P2P_0184!" "Jawa Timur" "Kota Probolinggo"
node prisma/create-pic.js PIC_KABKOTA "pic_jawa_t_surabaya" "P2P_0185!" "Jawa Timur" "Kota Surabaya"
Write-Host "  -- Kalimantan Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_bengkaya" "P2P_0186!" "Kalimantan Barat" "Kab. Bengkayang"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kapuas_h" "P2P_0187!" "Kalimantan Barat" "Kab. Kapuas Hulu"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kayong_u" "P2P_0188!" "Kalimantan Barat" "Kab. Kayong Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_ketapang" "P2P_0189!" "Kalimantan Barat" "Kab. Ketapang"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kubu_ray" "P2P_0190!" "Kalimantan Barat" "Kab. Kubu Raya"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_landak" "P2P_0191!" "Kalimantan Barat" "Kab. Landak"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_melawi" "P2P_0192!" "Kalimantan Barat" "Kab. Melawi"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_mempawah" "P2P_0193!" "Kalimantan Barat" "Kab. Mempawah"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_sambas" "P2P_0194!" "Kalimantan Barat" "Kab. Sambas"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_sanggau" "P2P_0195!" "Kalimantan Barat" "Kab. Sanggau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_sekadau" "P2P_0196!" "Kalimantan Barat" "Kab. Sekadau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_sintang" "P2P_0197!" "Kalimantan Barat" "Kab. Sintang"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_pontiana" "P2P_0198!" "Kalimantan Barat" "Kota Pontianak"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_singkawa" "P2P_0199!" "Kalimantan Barat" "Kota Singkawang"
Write-Host "  -- Kalimantan Selatan" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_balangan" "P2P_0200!" "Kalimantan Selatan" "Kab. Balangan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_banjar" "P2P_0201!" "Kalimantan Selatan" "Kab. Banjar"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_barito_k" "P2P_0202!" "Kalimantan Selatan" "Kab. Barito Kuala"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_hulu_sun" "P2P_0203!" "Kalimantan Selatan" "Kab. Hulu Sungai Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_hulu_sun" "P2P_0204!" "Kalimantan Selatan" "Kab. Hulu Sungai Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_hulu_sun" "P2P_0205!" "Kalimantan Selatan" "Kab. Hulu Sungai Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kotabaru" "P2P_0206!" "Kalimantan Selatan" "Kab. Kotabaru"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tabalong" "P2P_0207!" "Kalimantan Selatan" "Kab. Tabalong"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tanah_bu" "P2P_0208!" "Kalimantan Selatan" "Kab. Tanah Bumbu"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tanah_la" "P2P_0209!" "Kalimantan Selatan" "Kab. Tanah Laut"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tapin" "P2P_0210!" "Kalimantan Selatan" "Kab. Tapin"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_banjarba" "P2P_0211!" "Kalimantan Selatan" "Kota Banjarbaru"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_banjarma" "P2P_0212!" "Kalimantan Selatan" "Kota Banjarmasin"
Write-Host "  -- Kalimantan Tengah" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_barito_s" "P2P_0213!" "Kalimantan Tengah" "Kab. Barito Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_barito_t" "P2P_0214!" "Kalimantan Tengah" "Kab. Barito Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_barito_u" "P2P_0215!" "Kalimantan Tengah" "Kab. Barito Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_gunung_m" "P2P_0216!" "Kalimantan Tengah" "Kab. Gunung Mas"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kapuas" "P2P_0217!" "Kalimantan Tengah" "Kab. Kapuas"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_katingan" "P2P_0218!" "Kalimantan Tengah" "Kab. Katingan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kotawari" "P2P_0219!" "Kalimantan Tengah" "Kab. Kotawaringin Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kotawari" "P2P_0220!" "Kalimantan Tengah" "Kab. Kotawaringin Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_lamandau" "P2P_0221!" "Kalimantan Tengah" "Kab. Lamandau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_murung_r" "P2P_0222!" "Kalimantan Tengah" "Kab. Murung Raya"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_pulang_p" "P2P_0223!" "Kalimantan Tengah" "Kab. Pulang Pisau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_seruyan" "P2P_0224!" "Kalimantan Tengah" "Kab. Seruyan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_sukamara" "P2P_0225!" "Kalimantan Tengah" "Kab. Sukamara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_palangka" "P2P_0226!" "Kalimantan Tengah" "Kota Palangka Raya"
Write-Host "  -- Kalimantan Timur" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_berau" "P2P_0227!" "Kalimantan Timur" "Kab. Berau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kutai_ba" "P2P_0228!" "Kalimantan Timur" "Kab. Kutai Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kutai_ka" "P2P_0229!" "Kalimantan Timur" "Kab. Kutai Kartanegara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_kutai_ti" "P2P_0230!" "Kalimantan Timur" "Kab. Kutai Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_mahakam_" "P2P_0231!" "Kalimantan Timur" "Kab. Mahakam Ulu"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_paser" "P2P_0232!" "Kalimantan Timur" "Kab. Paser"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_penajam_" "P2P_0233!" "Kalimantan Timur" "Kab. Penajam Paser Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_balikpap" "P2P_0234!" "Kalimantan Timur" "Kota Balikpapan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_bontang" "P2P_0235!" "Kalimantan Timur" "Kota Bontang"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_samarind" "P2P_0236!" "Kalimantan Timur" "Kota Samarinda"
Write-Host "  -- Kalimantan Utara" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_bulungan" "P2P_0237!" "Kalimantan Utara" "Kab. Bulungan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_malinau" "P2P_0238!" "Kalimantan Utara" "Kab. Malinau"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_nunukan" "P2P_0239!" "Kalimantan Utara" "Kab. Nunukan"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tana_tid" "P2P_0240!" "Kalimantan Utara" "Kab. Tana Tidung"
node prisma/create-pic.js PIC_KABKOTA "pic_kalima_tarakan" "P2P_0241!" "Kalimantan Utara" "Kota Tarakan"
Write-Host "  -- Kepulauan Riau" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_bintan" "P2P_0242!" "Kepulauan Riau" "Kab. Bintan"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_karimun" "P2P_0243!" "Kepulauan Riau" "Kab. Karimun"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_kepulaua" "P2P_0244!" "Kepulauan Riau" "Kab. Kepulauan Anambas"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_lingga" "P2P_0245!" "Kepulauan Riau" "Kab. Lingga"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_natuna" "P2P_0246!" "Kepulauan Riau" "Kab. Natuna"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_batam" "P2P_0247!" "Kepulauan Riau" "Kota Batam"
node prisma/create-pic.js PIC_KABKOTA "pic_kepula_tanjungp" "P2P_0248!" "Kepulauan Riau" "Kota Tanjungpinang"
Write-Host "  -- Lampung" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_lampung_" "P2P_0249!" "Lampung" "Kab. Lampung Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_lampung_" "P2P_0250!" "Lampung" "Kab. Lampung Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_lampung_" "P2P_0251!" "Lampung" "Kab. Lampung Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_lampung_" "P2P_0252!" "Lampung" "Kab. Lampung Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_lampung_" "P2P_0253!" "Lampung" "Kab. Lampung Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_mesuji" "P2P_0254!" "Lampung" "Kab. Mesuji"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_pesawara" "P2P_0255!" "Lampung" "Kab. Pesawaran"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_pesisir_" "P2P_0256!" "Lampung" "Kab. Pesisir Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_pringsew" "P2P_0257!" "Lampung" "Kab. Pringsewu"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_tanggamu" "P2P_0258!" "Lampung" "Kab. Tanggamus"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_tulang_b" "P2P_0259!" "Lampung" "Kab. Tulang Bawang"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_tulang_b" "P2P_0260!" "Lampung" "Kab. Tulang Bawang Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_way_kana" "P2P_0261!" "Lampung" "Kab. Way Kanan"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_bandar_l" "P2P_0262!" "Lampung" "Kota Bandar Lampung"
node prisma/create-pic.js PIC_KABKOTA "pic_lampun_metro" "P2P_0263!" "Lampung" "Kota Metro"
Write-Host "  -- Maluku" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_buru" "P2P_0264!" "Maluku" "Kab. Buru"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_buru_sel" "P2P_0265!" "Maluku" "Kab. Buru Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_kepulaua" "P2P_0266!" "Maluku" "Kab. Kepulauan Aru"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_maluku_b" "P2P_0267!" "Maluku" "Kab. Maluku Barat Daya"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_maluku_t" "P2P_0268!" "Maluku" "Kab. Maluku Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_maluku_t" "P2P_0269!" "Maluku" "Kab. Maluku Tenggara"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_maluku_t" "P2P_0270!" "Maluku" "Kab. Maluku Tenggara Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_seram_ba" "P2P_0271!" "Maluku" "Kab. Seram Bagian Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_seram_ba" "P2P_0272!" "Maluku" "Kab. Seram Bagian Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_ambon" "P2P_0273!" "Maluku" "Kota Ambon"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_tual" "P2P_0274!" "Maluku" "Kota Tual"
Write-Host "  -- Maluku Utara" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_halmaher" "P2P_0275!" "Maluku Utara" "Kab. Halmahera Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_halmaher" "P2P_0276!" "Maluku Utara" "Kab. Halmahera Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_halmaher" "P2P_0277!" "Maluku Utara" "Kab. Halmahera Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_halmaher" "P2P_0278!" "Maluku Utara" "Kab. Halmahera Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_halmaher" "P2P_0279!" "Maluku Utara" "Kab. Halmahera Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_kepulaua" "P2P_0280!" "Maluku Utara" "Kab. Kepulauan Sula"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_pulau_mo" "P2P_0281!" "Maluku Utara" "Kab. Pulau Morotai"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_pulau_ta" "P2P_0282!" "Maluku Utara" "Kab. Pulau Taliabu"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_ternate" "P2P_0283!" "Maluku Utara" "Kota Ternate"
node prisma/create-pic.js PIC_KABKOTA "pic_maluku_tidore_k" "P2P_0284!" "Maluku Utara" "Kota Tidore Kepulauan"
Write-Host "  -- Nusa Tenggara Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_bima" "P2P_0285!" "Nusa Tenggara Barat" "Kab. Bima"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_dompu" "P2P_0286!" "Nusa Tenggara Barat" "Kab. Dompu"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_lombok_b" "P2P_0287!" "Nusa Tenggara Barat" "Kab. Lombok Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_lombok_t" "P2P_0288!" "Nusa Tenggara Barat" "Kab. Lombok Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_lombok_t" "P2P_0289!" "Nusa Tenggara Barat" "Kab. Lombok Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_lombok_u" "P2P_0290!" "Nusa Tenggara Barat" "Kab. Lombok Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumbawa" "P2P_0291!" "Nusa Tenggara Barat" "Kab. Sumbawa"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumbawa_" "P2P_0292!" "Nusa Tenggara Barat" "Kab. Sumbawa Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_bima" "P2P_0293!" "Nusa Tenggara Barat" "Kota Bima"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_mataram" "P2P_0294!" "Nusa Tenggara Barat" "Kota Mataram"
Write-Host "  -- Nusa Tenggara Timur" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_alor" "P2P_0295!" "Nusa Tenggara Timur" "Kab. Alor"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_belu" "P2P_0296!" "Nusa Tenggara Timur" "Kab. Belu"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_ende" "P2P_0297!" "Nusa Tenggara Timur" "Kab. Ende"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_flores_t" "P2P_0298!" "Nusa Tenggara Timur" "Kab. Flores Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_kupang" "P2P_0299!" "Nusa Tenggara Timur" "Kab. Kupang"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_lembata" "P2P_0300!" "Nusa Tenggara Timur" "Kab. Lembata"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_malaka" "P2P_0301!" "Nusa Tenggara Timur" "Kab. Malaka"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_manggara" "P2P_0302!" "Nusa Tenggara Timur" "Kab. Manggarai"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_manggara" "P2P_0303!" "Nusa Tenggara Timur" "Kab. Manggarai Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_manggara" "P2P_0304!" "Nusa Tenggara Timur" "Kab. Manggarai Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_nagekeo" "P2P_0305!" "Nusa Tenggara Timur" "Kab. Nagekeo"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_ngada" "P2P_0306!" "Nusa Tenggara Timur" "Kab. Ngada"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_rote_nda" "P2P_0307!" "Nusa Tenggara Timur" "Kab. Rote Ndao"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sabu_rai" "P2P_0308!" "Nusa Tenggara Timur" "Kab. Sabu Raijua"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sikka" "P2P_0309!" "Nusa Tenggara Timur" "Kab. Sikka"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumba_ba" "P2P_0310!" "Nusa Tenggara Timur" "Kab. Sumba Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumba_ba" "P2P_0311!" "Nusa Tenggara Timur" "Kab. Sumba Barat Daya"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumba_te" "P2P_0312!" "Nusa Tenggara Timur" "Kab. Sumba Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_sumba_ti" "P2P_0313!" "Nusa Tenggara Timur" "Kab. Sumba Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_timor_te" "P2P_0314!" "Nusa Tenggara Timur" "Kab. Timor Tengah Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_timor_te" "P2P_0315!" "Nusa Tenggara Timur" "Kab. Timor Tengah Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_nusa_t_kupang" "P2P_0316!" "Nusa Tenggara Timur" "Kota Kupang"
Write-Host "  -- Papua" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua_asmat" "P2P_0317!" "Papua" "Kab. Asmat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_biak_num" "P2P_0318!" "Papua" "Kab. Biak Numfor"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_boven_di" "P2P_0319!" "Papua" "Kab. Boven Digoel"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_deiyai" "P2P_0320!" "Papua" "Kab. Deiyai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_dogiyai" "P2P_0321!" "Papua" "Kab. Dogiyai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_intan_ja" "P2P_0322!" "Papua" "Kab. Intan Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_jayapura" "P2P_0323!" "Papua" "Kab. Jayapura"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_jayawija" "P2P_0324!" "Papua" "Kab. Jayawijaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_keerom" "P2P_0325!" "Papua" "Kab. Keerom"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_kepulaua" "P2P_0326!" "Papua" "Kab. Kepulauan Yapen"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_lanny_ja" "P2P_0327!" "Papua" "Kab. Lanny Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_mamberam" "P2P_0328!" "Papua" "Kab. Mamberamo Raya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_mamberam" "P2P_0329!" "Papua" "Kab. Mamberamo Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_mappi" "P2P_0330!" "Papua" "Kab. Mappi"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_merauke" "P2P_0331!" "Papua" "Kab. Merauke"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_mimika" "P2P_0332!" "Papua" "Kab. Mimika"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_nabire" "P2P_0333!" "Papua" "Kab. Nabire"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_nduga" "P2P_0334!" "Papua" "Kab. Nduga"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_paniai" "P2P_0335!" "Papua" "Kab. Paniai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_pegunung" "P2P_0336!" "Papua" "Kab. Pegunungan Bintang"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_puncak" "P2P_0337!" "Papua" "Kab. Puncak"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_puncak_j" "P2P_0338!" "Papua" "Kab. Puncak Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_sarmi" "P2P_0339!" "Papua" "Kab. Sarmi"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_supiori" "P2P_0340!" "Papua" "Kab. Supiori"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_tolikara" "P2P_0341!" "Papua" "Kab. Tolikara"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_waropen" "P2P_0342!" "Papua" "Kab. Waropen"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_yahukimo" "P2P_0343!" "Papua" "Kab. Yahukimo"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_yalimo" "P2P_0344!" "Papua" "Kab. Yalimo"
node prisma/create-pic.js PIC_KABKOTA "pic_papua_jayapura" "P2P_0345!" "Papua" "Kota Jayapura"
Write-Host "  -- Papua Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua__fakfak" "P2P_0346!" "Papua Barat" "Kab. Fakfak"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__kaimana" "P2P_0347!" "Papua Barat" "Kab. Kaimana"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__manokwar" "P2P_0348!" "Papua Barat" "Kab. Manokwari"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__manokwar" "P2P_0349!" "Papua Barat" "Kab. Manokwari Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__maybrat" "P2P_0350!" "Papua Barat" "Kab. Maybrat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__pegunung" "P2P_0351!" "Papua Barat" "Kab. Pegunungan Arfak"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__raja_amp" "P2P_0352!" "Papua Barat" "Kab. Raja Ampat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong" "P2P_0353!" "Papua Barat" "Kab. Sorong"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong_s" "P2P_0354!" "Papua Barat" "Kab. Sorong Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__tambrauw" "P2P_0355!" "Papua Barat" "Kab. Tambrauw"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__teluk_bi" "P2P_0356!" "Papua Barat" "Kab. Teluk Bintuni"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__teluk_wo" "P2P_0357!" "Papua Barat" "Kab. Teluk Wondama"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong" "P2P_0358!" "Papua Barat" "Kota Sorong"
Write-Host "  -- Papua Barat Daya" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua__maybrat" "P2P_0359!" "Papua Barat Daya" "Kab. Maybrat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__raja_amp" "P2P_0360!" "Papua Barat Daya" "Kab. Raja Ampat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong" "P2P_0361!" "Papua Barat Daya" "Kab. Sorong"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong_s" "P2P_0362!" "Papua Barat Daya" "Kab. Sorong Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__tambrauw" "P2P_0363!" "Papua Barat Daya" "Kab. Tambrauw"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__sorong" "P2P_0364!" "Papua Barat Daya" "Kota Sorong"
Write-Host "  -- Papua Pegunungan" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua__jayawija" "P2P_0365!" "Papua Pegunungan" "Kab. Jayawijaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__lanny_ja" "P2P_0366!" "Papua Pegunungan" "Kab. Lanny Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__mamberam" "P2P_0367!" "Papua Pegunungan" "Kab. Mamberamo Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__nduga" "P2P_0368!" "Papua Pegunungan" "Kab. Nduga"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__pegunung" "P2P_0369!" "Papua Pegunungan" "Kab. Pegunungan Bintang"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__tolikara" "P2P_0370!" "Papua Pegunungan" "Kab. Tolikara"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__yahukimo" "P2P_0371!" "Papua Pegunungan" "Kab. Yahukimo"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__yalimo" "P2P_0372!" "Papua Pegunungan" "Kab. Yalimo"
Write-Host "  -- Papua Selatan" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua__asmat" "P2P_0373!" "Papua Selatan" "Kab. Asmat"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__boven_di" "P2P_0374!" "Papua Selatan" "Kab. Boven Digoel"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__mappi" "P2P_0375!" "Papua Selatan" "Kab. Mappi"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__merauke" "P2P_0376!" "Papua Selatan" "Kab. Merauke"
Write-Host "  -- Papua Tengah" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_papua__deiyai" "P2P_0377!" "Papua Tengah" "Kab. Deiyai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__dogiyai" "P2P_0378!" "Papua Tengah" "Kab. Dogiyai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__intan_ja" "P2P_0379!" "Papua Tengah" "Kab. Intan Jaya"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__mimika" "P2P_0380!" "Papua Tengah" "Kab. Mimika"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__nabire" "P2P_0381!" "Papua Tengah" "Kab. Nabire"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__paniai" "P2P_0382!" "Papua Tengah" "Kab. Paniai"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__puncak" "P2P_0383!" "Papua Tengah" "Kab. Puncak"
node prisma/create-pic.js PIC_KABKOTA "pic_papua__puncak_j" "P2P_0384!" "Papua Tengah" "Kab. Puncak Jaya"
Write-Host "  -- Riau" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_riau_bengkali" "P2P_0385!" "Riau" "Kab. Bengkalis"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_indragir" "P2P_0386!" "Riau" "Kab. Indragiri Hilir"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_indragir" "P2P_0387!" "Riau" "Kab. Indragiri Hulu"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_kampar" "P2P_0388!" "Riau" "Kab. Kampar"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_kepulaua" "P2P_0389!" "Riau" "Kab. Kepulauan Meranti"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_kuantan_" "P2P_0390!" "Riau" "Kab. Kuantan Singingi"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_pelalawa" "P2P_0391!" "Riau" "Kab. Pelalawan"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_rokan_hi" "P2P_0392!" "Riau" "Kab. Rokan Hilir"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_rokan_hu" "P2P_0393!" "Riau" "Kab. Rokan Hulu"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_siak" "P2P_0394!" "Riau" "Kab. Siak"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_dumai" "P2P_0395!" "Riau" "Kota Dumai"
node prisma/create-pic.js PIC_KABKOTA "pic_riau_pekanbar" "P2P_0396!" "Riau" "Kota Pekanbaru"
Write-Host "  -- Sulawesi Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_majene" "P2P_0397!" "Sulawesi Barat" "Kab. Majene"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_mamasa" "P2P_0398!" "Sulawesi Barat" "Kab. Mamasa"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_mamuju" "P2P_0399!" "Sulawesi Barat" "Kab. Mamuju"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_mamuju_t" "P2P_0400!" "Sulawesi Barat" "Kab. Mamuju Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_pasangka" "P2P_0401!" "Sulawesi Barat" "Kab. Pasangkayu"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_polewali" "P2P_0402!" "Sulawesi Barat" "Kab. Polewali Mandar"
Write-Host "  -- Sulawesi Selatan" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bantaeng" "P2P_0403!" "Sulawesi Selatan" "Kab. Bantaeng"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_barru" "P2P_0404!" "Sulawesi Selatan" "Kab. Barru"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bone" "P2P_0405!" "Sulawesi Selatan" "Kab. Bone"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bulukumb" "P2P_0406!" "Sulawesi Selatan" "Kab. Bulukumba"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_enrekang" "P2P_0407!" "Sulawesi Selatan" "Kab. Enrekang"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_gowa" "P2P_0408!" "Sulawesi Selatan" "Kab. Gowa"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_jenepont" "P2P_0409!" "Sulawesi Selatan" "Kab. Jeneponto"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kepulaua" "P2P_0410!" "Sulawesi Selatan" "Kab. Kepulauan Selayar"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_luwu" "P2P_0411!" "Sulawesi Selatan" "Kab. Luwu"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_luwu_tim" "P2P_0412!" "Sulawesi Selatan" "Kab. Luwu Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_luwu_uta" "P2P_0413!" "Sulawesi Selatan" "Kab. Luwu Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_maros" "P2P_0414!" "Sulawesi Selatan" "Kab. Maros"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_pangkaje" "P2P_0415!" "Sulawesi Selatan" "Kab. Pangkajene dan Kepulauan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_pinrang" "P2P_0416!" "Sulawesi Selatan" "Kab. Pinrang"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_sidenren" "P2P_0417!" "Sulawesi Selatan" "Kab. Sidenreng Rappang"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_sinjai" "P2P_0418!" "Sulawesi Selatan" "Kab. Sinjai"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_soppeng" "P2P_0419!" "Sulawesi Selatan" "Kab. Soppeng"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_takalar" "P2P_0420!" "Sulawesi Selatan" "Kab. Takalar"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_tana_tor" "P2P_0421!" "Sulawesi Selatan" "Kab. Tana Toraja"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_toraja_u" "P2P_0422!" "Sulawesi Selatan" "Kab. Toraja Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_wajo" "P2P_0423!" "Sulawesi Selatan" "Kab. Wajo"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_makassar" "P2P_0424!" "Sulawesi Selatan" "Kota Makassar"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_palopo" "P2P_0425!" "Sulawesi Selatan" "Kota Palopo"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_parepare" "P2P_0426!" "Sulawesi Selatan" "Kota Parepare"
Write-Host "  -- Sulawesi Tengah" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_banggai" "P2P_0427!" "Sulawesi Tengah" "Kab. Banggai"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_banggai_" "P2P_0428!" "Sulawesi Tengah" "Kab. Banggai Kepulauan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_banggai_" "P2P_0429!" "Sulawesi Tengah" "Kab. Banggai Laut"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_buol" "P2P_0430!" "Sulawesi Tengah" "Kab. Buol"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_donggala" "P2P_0431!" "Sulawesi Tengah" "Kab. Donggala"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_morowali" "P2P_0432!" "Sulawesi Tengah" "Kab. Morowali"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_morowali" "P2P_0433!" "Sulawesi Tengah" "Kab. Morowali Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_parigi_m" "P2P_0434!" "Sulawesi Tengah" "Kab. Parigi Moutong"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_poso" "P2P_0435!" "Sulawesi Tengah" "Kab. Poso"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_sigi" "P2P_0436!" "Sulawesi Tengah" "Kab. Sigi"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_tojo_una" "P2P_0437!" "Sulawesi Tengah" "Kab. Tojo Una-Una"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_tolitoli" "P2P_0438!" "Sulawesi Tengah" "Kab. Toli-Toli"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_palu" "P2P_0439!" "Sulawesi Tengah" "Kota Palu"
Write-Host "  -- Sulawesi Tenggara" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bombana" "P2P_0440!" "Sulawesi Tenggara" "Kab. Bombana"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_buton" "P2P_0441!" "Sulawesi Tenggara" "Kab. Buton"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_buton_se" "P2P_0442!" "Sulawesi Tenggara" "Kab. Buton Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_buton_te" "P2P_0443!" "Sulawesi Tenggara" "Kab. Buton Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_buton_ut" "P2P_0444!" "Sulawesi Tenggara" "Kab. Buton Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kolaka" "P2P_0445!" "Sulawesi Tenggara" "Kab. Kolaka"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kolaka_t" "P2P_0446!" "Sulawesi Tenggara" "Kab. Kolaka Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kolaka_u" "P2P_0447!" "Sulawesi Tenggara" "Kab. Kolaka Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_konawe" "P2P_0448!" "Sulawesi Tenggara" "Kab. Konawe"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_konawe_k" "P2P_0449!" "Sulawesi Tenggara" "Kab. Konawe Kepulauan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_konawe_s" "P2P_0450!" "Sulawesi Tenggara" "Kab. Konawe Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_konawe_u" "P2P_0451!" "Sulawesi Tenggara" "Kab. Konawe Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_muna" "P2P_0452!" "Sulawesi Tenggara" "Kab. Muna"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_muna_bar" "P2P_0453!" "Sulawesi Tenggara" "Kab. Muna Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_wakatobi" "P2P_0454!" "Sulawesi Tenggara" "Kab. Wakatobi"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_baubau" "P2P_0455!" "Sulawesi Tenggara" "Kota Bau-Bau"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kendari" "P2P_0456!" "Sulawesi Tenggara" "Kota Kendari"
Write-Host "  -- Sulawesi Utara" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bolaang_" "P2P_0457!" "Sulawesi Utara" "Kab. Bolaang Mongondow"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bolaang_" "P2P_0458!" "Sulawesi Utara" "Kab. Bolaang Mongondow Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bolaang_" "P2P_0459!" "Sulawesi Utara" "Kab. Bolaang Mongondow Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bolaang_" "P2P_0460!" "Sulawesi Utara" "Kab. Bolaang Mongondow Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kepulaua" "P2P_0461!" "Sulawesi Utara" "Kab. Kepulauan Sangihe"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kepulaua" "P2P_0462!" "Sulawesi Utara" "Kab. Kepulauan Siau Tagulandang Biaro"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kepulaua" "P2P_0463!" "Sulawesi Utara" "Kab. Kepulauan Talaud"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_minahasa" "P2P_0464!" "Sulawesi Utara" "Kab. Minahasa"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_minahasa" "P2P_0465!" "Sulawesi Utara" "Kab. Minahasa Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_minahasa" "P2P_0466!" "Sulawesi Utara" "Kab. Minahasa Tenggara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_minahasa" "P2P_0467!" "Sulawesi Utara" "Kab. Minahasa Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_bitung" "P2P_0468!" "Sulawesi Utara" "Kota Bitung"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_kotamoba" "P2P_0469!" "Sulawesi Utara" "Kota Kotamobagu"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_manado" "P2P_0470!" "Sulawesi Utara" "Kota Manado"
node prisma/create-pic.js PIC_KABKOTA "pic_sulawe_tomohon" "P2P_0471!" "Sulawesi Utara" "Kota Tomohon"
Write-Host "  -- Sumatera Barat" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_agam" "P2P_0472!" "Sumatera Barat" "Kab. Agam"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_dharmasr" "P2P_0473!" "Sumatera Barat" "Kab. Dharmasraya"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_kepulaua" "P2P_0474!" "Sumatera Barat" "Kab. Kepulauan Mentawai"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_lima_pul" "P2P_0475!" "Sumatera Barat" "Kab. Lima Puluh Kota"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padang_p" "P2P_0476!" "Sumatera Barat" "Kab. Padang Pariaman"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pasaman" "P2P_0477!" "Sumatera Barat" "Kab. Pasaman"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pasaman_" "P2P_0478!" "Sumatera Barat" "Kab. Pasaman Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pesisir_" "P2P_0479!" "Sumatera Barat" "Kab. Pesisir Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_sijunjun" "P2P_0480!" "Sumatera Barat" "Kab. Sijunjung"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_solok" "P2P_0481!" "Sumatera Barat" "Kab. Solok"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_solok_se" "P2P_0482!" "Sumatera Barat" "Kab. Solok Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tanah_da" "P2P_0483!" "Sumatera Barat" "Kab. Tanah Datar"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_bukittin" "P2P_0484!" "Sumatera Barat" "Kota Bukittinggi"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padang" "P2P_0485!" "Sumatera Barat" "Kota Padang"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padang_p" "P2P_0486!" "Sumatera Barat" "Kota Padang Panjang"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pariaman" "P2P_0487!" "Sumatera Barat" "Kota Pariaman"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_payakumb" "P2P_0488!" "Sumatera Barat" "Kota Payakumbuh"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_sawahlun" "P2P_0489!" "Sumatera Barat" "Kota Sawahlunto"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_solok" "P2P_0490!" "Sumatera Barat" "Kota Solok"
Write-Host "  -- Sumatera Selatan" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_banyuasi" "P2P_0491!" "Sumatera Selatan" "Kab. Banyuasin"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_empat_la" "P2P_0492!" "Sumatera Selatan" "Kab. Empat Lawang"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_lahat" "P2P_0493!" "Sumatera Selatan" "Kab. Lahat"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_muara_en" "P2P_0494!" "Sumatera Selatan" "Kab. Muara Enim"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_musi_ban" "P2P_0495!" "Sumatera Selatan" "Kab. Musi Banyuasin"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_musi_raw" "P2P_0496!" "Sumatera Selatan" "Kab. Musi Rawas"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_musi_raw" "P2P_0497!" "Sumatera Selatan" "Kab. Musi Rawas Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_ogan_ili" "P2P_0498!" "Sumatera Selatan" "Kab. Ogan Ilir"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_ogan_kom" "P2P_0499!" "Sumatera Selatan" "Kab. Ogan Komering Ilir"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_ogan_kom" "P2P_0500!" "Sumatera Selatan" "Kab. Ogan Komering Ulu"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_ogan_kom" "P2P_0501!" "Sumatera Selatan" "Kab. Ogan Komering Ulu Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_ogan_kom" "P2P_0502!" "Sumatera Selatan" "Kab. Ogan Komering Ulu Timur"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_penukal_" "P2P_0503!" "Sumatera Selatan" "Kab. Penukal Abab Lematang Ilir"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_lubuklin" "P2P_0504!" "Sumatera Selatan" "Kota Lubuklinggau"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pagar_al" "P2P_0505!" "Sumatera Selatan" "Kota Pagar Alam"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_palemban" "P2P_0506!" "Sumatera Selatan" "Kota Palembang"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_prabumul" "P2P_0507!" "Sumatera Selatan" "Kota Prabumulih"
Write-Host "  -- Sumatera Utara" -ForegroundColor Gray
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_asahan" "P2P_0508!" "Sumatera Utara" "Kab. Asahan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_batu_bar" "P2P_0509!" "Sumatera Utara" "Kab. Batu Bara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_dairi" "P2P_0510!" "Sumatera Utara" "Kab. Dairi"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_deli_ser" "P2P_0511!" "Sumatera Utara" "Kab. Deli Serdang"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_humbang_" "P2P_0512!" "Sumatera Utara" "Kab. Humbang Hasundutan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_karo" "P2P_0513!" "Sumatera Utara" "Kab. Karo"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_labuhanb" "P2P_0514!" "Sumatera Utara" "Kab. Labuhanbatu"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_labuhanb" "P2P_0515!" "Sumatera Utara" "Kab. Labuhanbatu Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_labuhanb" "P2P_0516!" "Sumatera Utara" "Kab. Labuhanbatu Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_langkat" "P2P_0517!" "Sumatera Utara" "Kab. Langkat"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_mandaili" "P2P_0518!" "Sumatera Utara" "Kab. Mandailing Natal"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_nias" "P2P_0519!" "Sumatera Utara" "Kab. Nias"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_nias_bar" "P2P_0520!" "Sumatera Utara" "Kab. Nias Barat"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_nias_sel" "P2P_0521!" "Sumatera Utara" "Kab. Nias Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_nias_uta" "P2P_0522!" "Sumatera Utara" "Kab. Nias Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padang_l" "P2P_0523!" "Sumatera Utara" "Kab. Padang Lawas"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padang_l" "P2P_0524!" "Sumatera Utara" "Kab. Padang Lawas Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pakpak_b" "P2P_0525!" "Sumatera Utara" "Kab. Pakpak Bharat"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_samosir" "P2P_0526!" "Sumatera Utara" "Kab. Samosir"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_serdang_" "P2P_0527!" "Sumatera Utara" "Kab. Serdang Bedagai"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_simalung" "P2P_0528!" "Sumatera Utara" "Kab. Simalungun"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tapanuli" "P2P_0529!" "Sumatera Utara" "Kab. Tapanuli Selatan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tapanuli" "P2P_0530!" "Sumatera Utara" "Kab. Tapanuli Tengah"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tapanuli" "P2P_0531!" "Sumatera Utara" "Kab. Tapanuli Utara"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_toba" "P2P_0532!" "Sumatera Utara" "Kab. Toba"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_binjai" "P2P_0533!" "Sumatera Utara" "Kota Binjai"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_gunungsi" "P2P_0534!" "Sumatera Utara" "Kota Gunungsitoli"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_medan" "P2P_0535!" "Sumatera Utara" "Kota Medan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_padangsi" "P2P_0536!" "Sumatera Utara" "Kota Padangsidimpuan"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_pematang" "P2P_0537!" "Sumatera Utara" "Kota Pematangsiantar"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_sibolga" "P2P_0538!" "Sumatera Utara" "Kota Sibolga"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tanjungb" "P2P_0539!" "Sumatera Utara" "Kota Tanjungbalai"
node prisma/create-pic.js PIC_KABKOTA "pic_sumate_tebing_t" "P2P_0540!" "Sumatera Utara" "Kota Tebing Tinggi"

Write-Host "" 
Write-Host "Selesai! Total 540 akun PIC Kabupaten/Kota + 38 PIC Provinsi dibuat." -ForegroundColor Green
